#CCE_Board_Definitions:BMI085;BMI088

COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= bmi08x_read_sensor_data.c

API_LOCATION ?= ../../../bmi08x

C_SRCS += \
$(API_LOCATION)/bmi08a.c \
$(API_LOCATION)/bmi08g.c \

INCLUDEPATHS += \
$(API_LOCATION) \

include $(COINES_INSTALL_PATH)/coines.mk
